name: Compile and Distribute HeHeSPY Executables

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Create directory for compiled executables
        run: mkdir dist

      - name: Find and compile Python executables
        shell: pwsh
        run: |
          $pythonFiles = Get-ChildItem -Path $directory -Filter *.py
      
          # Iterate through each Python file and run pyinstaller
          foreach ($file in $pythonFiles) {
              # Construct the pyinstaller command for each file
              $pyinstallerCommand = "pyinstaller --onefile `"$($file.FullName)`" --distpath dist"
          
              # Run pyinstaller command
              Write-Output "Running pyinstaller for $($file.Name)..."
              Invoke-Expression -Command $pyinstallerCommand
          
              # Optionally, you can add more logic or output here
              # For example, check if pyinstaller command was successful
              # if ($?) { Write-Output "Pyinstaller successfully ran for $($file.Name)" }
          }



      - name: Archive compiled executables
        uses: actions/upload-artifact@v2
        with:
          name: compiled-scripts
          path: dist
